### PR TITLE
ZF3 Support, Short array syntax

### PR DESCRIPTION
**Pull request by MatthiasKuehneEllerhold**
I've made the logger module compatible with ZF3 and cleaned up some code.

The view script in particular was broken because the span.zdt-toolbar-info was missing even though the closing tag was still there?

Ive edited the composer.json as well to allow consumers to use stable version.

### CODE REVIEW

**Comment by MatthiasKuehneEllerhold** [comment]
Any news on this PR?

**Comment by jhuet** [comment]
Hi @MatthiasKuehneEllerhold, i was actually waiting for @RenatMagadiev to review this as i asked in the issue #5 he created. I don't have any news from him so i guess i'll trust you on this :)

**Comment by RenatMagadiev** [comment]
i'll check @MatthiasKuehneEllerhold PR and close #5. Thank you.

**Comment by jhuet** [comment]
Alright, i'll merge this PR then. Thank you both.

**Comment by MatthiasKuehneEllerhold** [comment]
Yay! Thanks :)

**Pull request merged**
